### PR TITLE
now with actual forms!

### PR DESCRIPTION
**Pull request by notwaldorf**
Subbed in a working `iron-form` for a plain div container. Also added a `name` attribute to all the fields so that they can actually be submitted.

### CODE REVIEW

**Comment by notwaldorf** [comment]
@morethanreal do you think all these elements should have "default" `name` attributes, or is that too overreaching?

**Comment by morethanreal** [comment]
IMO it should be up to the user to set the `name`.

**Comment by morethanreal** [comment]
lgtm

**Comment by notwaldorf** [comment]
Awesome, thanks!

**Pull request merged**
